// CarTalk Pro - 車両データベース
const CAR_DATABASE = [
  {
    id: 1, maker: "トヨタ", name: "プリウス", type: "セダン/HB", years: "2023〜現行(60系)",
    newPrice: "275〜392万円", engine: "1.8L/2.0L ハイブリッド", fuel: "ハイブリッド(レギュラー)",
    fuelEco: "28.6〜32.6km/L(WLTC)", drive: "FF/4WD",
    length: "4,600mm", width: "1,780mm", height: "1,420〜1,430mm", weight: "1,360〜1,520kg",
    seats: 5, trunk: "約410L",
    features: ["第5世代ハイブリッド", "19インチ大径ホイール", "プラグインHVあり", "ソーラールーフオプション"],
    talkPoints: ["歴代で最もスポーティなデザインで若い世代にも人気", "燃費は軽自動車並みで家計に優しい", "PHEVモデルなら自宅充電で近距離はEV走行可能", "安全装備Toyota Safety Sense最新版搭載"],
    rivals: ["ホンダ インサイト", "マツダ MAZDA3", "日産 ノート"],
    emoji: "🚗", popular: true
  },
  {
    id: 2, maker: "トヨタ", name: "ヤリス", type: "コンパクト", years: "2020〜現行",
    newPrice: "150〜253万円", engine: "1.0L/1.5L/1.5L HV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "20.2〜36.0km/L(WLTC)", drive: "FF/4WD",
    length: "3,940mm", width: "1,695mm", height: "1,500mm", weight: "940〜1,180kg",
    seats: 5, trunk: "約270L",
    features: ["TNGAプラットフォーム", "世界トップクラス低燃費", "GRヤリスも展開", "先進安全装備標準"],
    talkPoints: ["WRCで鍛えられた走りの良さが街乗りでも実感できる", "ハイブリッドならリッター36kmと驚異の燃費", "コンパクトで取り回し抜群、狭い道も安心", "GRヤリスはモータースポーツ直系で走り好きに大人気"],
    rivals: ["ホンダ フィット", "日産 ノート", "マツダ MAZDA2"],
    emoji: "🚙", popular: true
  },
  {
    id: 3, maker: "トヨタ", name: "アルファード", type: "ミニバン", years: "2023〜現行(40系)",
    newPrice: "540〜872万円", engine: "2.5L HV/2.4Lターボ", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "14.8〜17.7km/L(WLTC)", drive: "FF/4WD",
    length: "4,995mm", width: "1,850mm", height: "1,935mm", weight: "2,060〜2,320kg",
    seats: 7, trunk: "大容量",
    features: ["最上級ミニバン", "Executive Loungeシート", "デジタルインナーミラー", "パワーバックドア"],
    talkPoints: ["日本が世界に誇る最高級ミニバン、VIPの送迎にも使われる", "2列目シートは飛行機のファーストクラス並みの快適さ", "リセールバリューが極めて高く資産価値がある", "家族の大切な時間を最高の空間で過ごせる"],
    rivals: ["日産 エルグランド", "ホンダ オデッセイ", "トヨタ ヴェルファイア"],
    emoji: "🚐", popular: true
  },
  {
    id: 4, maker: "トヨタ", name: "ヴォクシー", type: "ミニバン", years: "2022〜現行(90系)",
    newPrice: "309〜396万円", engine: "2.0L/1.8L HV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "15.0〜23.0km/L(WLTC)", drive: "FF/4WD",
    length: "4,695mm", width: "1,730mm", height: "1,895mm", weight: "1,600〜1,720kg",
    seats: 7, trunk: "大容量スライド式",
    features: ["ファミリー向けミニバン", "両側パワースライドドア", "低床フラットフロア", "Toyota Safety Sense"],
    talkPoints: ["子育て世代に圧倒的人気、送り迎えから旅行まで万能", "スライドドアで狭い駐車場でも乗り降りラクラク", "3列目を跳ね上げれば大きな荷物も楽々積める", "ハイブリッドなら燃費も良好で維持費を抑えられる"],
    rivals: ["日産 セレナ", "ホンダ ステップワゴン", "トヨタ ノア"],
    emoji: "🚐", popular: true
  },
  {
    id: 5, maker: "トヨタ", name: "ハリアー", type: "SUV", years: "2020〜現行(80系)",
    newPrice: "312〜504万円", engine: "2.0L/2.5L HV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "15.4〜22.3km/L(WLTC)", drive: "FF/4WD",
    length: "4,740mm", width: "1,855mm", height: "1,660mm", weight: "1,530〜1,840kg",
    seats: 5, trunk: "約409L",
    features: ["都市型プレミアムSUV", "流麗なクーペスタイル", "調光パノラマルーフ", "JBLサウンド"],
    talkPoints: ["エレガントなデザインで都会の街並みに映える", "調光ガラスルーフは透明から曇りガラスに切替可能", "乗り心地が上質で長距離ドライブも疲れにくい", "高級感がありながらレクサスより手が届きやすい価格帯"],
    rivals: ["日産 エクストレイル", "マツダ CX-5", "ホンダ ZR-V"],
    emoji: "🚙", popular: true
  },
  {
    id: 6, maker: "トヨタ", name: "ランドクルーザー300", type: "SUV", years: "2021〜現行",
    newPrice: "510〜800万円", engine: "3.5Lツインターボ/3.3Lディーゼルターボ", fuel: "ガソリン(ハイオク)/ディーゼル",
    fuelEco: "7.9〜9.7km/L(WLTC)", drive: "4WD",
    length: "4,985mm", width: "1,980mm", height: "1,925mm", weight: "2,360〜2,530kg",
    seats: 7, trunk: "大容量",
    features: ["世界最高峰の本格SUV", "ラダーフレーム構造", "マルチテレインセレクト", "指紋認証エンジンスタート"],
    talkPoints: ["70年以上の歴史を持つ世界が認めた本格SUV", "砂漠から雪山まで地球上どこでも走れる信頼性", "リセールバリューは驚異的、値落ちしにくい車の代表格", "ディーゼルモデルはトルクフルで力強い走り"],
    rivals: ["日産 パトロール", "三菱 パジェロ", "レクサス LX"],
    emoji: "🚙", popular: true
  },
  {
    id: 7, maker: "トヨタ", name: "カローラクロス", type: "SUV", years: "2021〜現行",
    newPrice: "218〜345万円", engine: "1.8L/1.8L HV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "14.4〜26.2km/L(WLTC)", drive: "FF/4WD",
    length: "4,490mm", width: "1,825mm", height: "1,620mm", weight: "1,330〜1,440kg",
    seats: 5, trunk: "約487L",
    features: ["ちょうどいいサイズSUV", "クラストップ荷室", "ディスプレイオーディオ", "コネクティッド機能"],
    talkPoints: ["カローラの信頼性とSUVの使い勝手を両立", "荷室はクラストップの広さでアウトドアに最適", "ハイブリッドなら燃費26km/L超えで経済的", "手頃な価格で充実装備、コスパ最強SUV"],
    rivals: ["ホンダ ヴェゼル", "マツダ CX-30", "日産 キックス"],
    emoji: "🚙", popular: false
  },
  {
    id: 8, maker: "トヨタ", name: "ノア", type: "ミニバン", years: "2022〜現行(90系)",
    newPrice: "267〜389万円", engine: "2.0L/1.8L HV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "15.0〜23.4km/L(WLTC)", drive: "FF/4WD",
    length: "4,695mm", width: "1,730mm", height: "1,895mm", weight: "1,600〜1,720kg",
    seats: 7, trunk: "大容量",
    features: ["ファミリーミニバン", "ユニバーサルステップ", "両側パワースライドドア", "アドバンストパーク"],
    talkPoints: ["ヴォクシーの兄弟車で落ち着いたデザインが人気", "自動駐車機能で大きな車でも駐車が安心", "シートアレンジが多彩で様々な使い方に対応", "ヴォクシーより少しお手頃な価格設定"],
    rivals: ["日産 セレナ", "ホンダ ステップワゴン", "トヨタ ヴォクシー"],
    emoji: "🚐", popular: false
  },
  {
    id: 9, maker: "トヨタ", name: "シエンタ", type: "ミニバン", years: "2022〜現行(10系)",
    newPrice: "195〜310万円", engine: "1.5L/1.5L HV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "18.3〜28.8km/L(WLTC)", drive: "FF/E-Four",
    length: "4,260mm", width: "1,695mm", height: "1,695mm", weight: "1,120〜1,330kg",
    seats: 7, trunk: "コンパクト3列",
    features: ["コンパクトミニバン", "5ナンバーサイズ", "低床フロア", "丸みのあるデザイン"],
    talkPoints: ["5ナンバーで扱いやすいのに3列シートで7人乗れる", "可愛らしいデザインで男女問わず好評", "燃費28km/L超えでミニバンの常識を覆す経済性", "子どもの送迎からレジャーまでちょうどいいサイズ感"],
    rivals: ["ホンダ フリード", "スズキ ソリオ"],
    emoji: "🚐", popular: true
  },
  {
    id: 10, maker: "トヨタ", name: "クラウン", type: "セダン/クロスオーバー", years: "2022〜現行(16代目)",
    newPrice: "435〜640万円", engine: "2.5L HV/2.4Lターボ HV", fuel: "ハイブリッド(レギュラー)",
    fuelEco: "15.7〜22.4km/L(WLTC)", drive: "FF/4WD",
    length: "4,930mm", width: "1,840mm", height: "1,540mm", weight: "1,750〜1,920kg",
    seats: 5, trunk: "約450L",
    features: ["クロスオーバースタイル", "デュアルブーストHV", "21インチホイール", "デジタルキー"],
    talkPoints: ["16代目は大胆にクロスオーバーに変身、話題性抜群", "日本の高級車の代名詞、60年以上の歴史と伝統", "2.4Lターボは0-100km/h 5.6秒の俊足", "セダン・スポーツ・エステートと4タイプ展開"],
    rivals: ["日産 スカイライン", "レクサス IS", "ホンダ アコード"],
    emoji: "🚗", popular: true
  },
  {
    id: 11, maker: "ホンダ", name: "N-BOX", type: "軽自動車", years: "2023〜現行(3代目)",
    newPrice: "164〜236万円", engine: "660cc/660ccターボ", fuel: "ガソリン(レギュラー)",
    fuelEco: "19.4〜21.6km/L(WLTC)", drive: "FF/4WD",
    length: "3,395mm", width: "1,475mm", height: "1,790mm", weight: "900〜1,010kg",
    seats: 4, trunk: "広々ハイトワゴン",
    features: ["日本一売れている車", "Honda SENSING標準", "センタータンクレイアウト", "助手席スーパースライド"],
    talkPoints: ["何年も連続で日本で一番売れている大人気車", "軽自動車とは思えない広い室内空間に驚く方が多い", "Honda SENSINGで安全性能は普通車並み", "維持費が安く税金も軽自動車税でお得"],
    rivals: ["ダイハツ タント", "スズキ スペーシア", "日産 ルークス"],
    emoji: "🚗", popular: true
  },
  {
    id: 12, maker: "ホンダ", name: "フィット", type: "コンパクト", years: "2020〜現行(4代目)",
    newPrice: "162〜266万円", engine: "1.5L/1.5L e:HEV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "17.0〜30.2km/L(WLTC)", drive: "FF/4WD",
    length: "3,995mm", width: "1,695mm", height: "1,515mm", weight: "1,080〜1,230kg",
    seats: 5, trunk: "約306L",
    features: ["5タイプ展開", "2モーターHV", "視界の良さ", "センタータンクレイアウト"],
    talkPoints: ["BASIC/HOME/RS/LUXE/CROSSTARと5つの個性から選べる", "極細Aピラーで視界が広く運転しやすいと好評", "後席の広さはクラスを超えた快適性", "e:HEVの走りはモーター主体でスムーズ"],
    rivals: ["トヨタ ヤリス", "日産 ノート", "マツダ MAZDA2"],
    emoji: "🚗", popular: true
  },
  {
    id: 13, maker: "ホンダ", name: "ヴェゼル", type: "SUV", years: "2021〜現行(2代目)",
    newPrice: "265〜330万円", engine: "1.5L/1.5L e:HEV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "15.0〜25.0km/L(WLTC)", drive: "FF/4WD",
    length: "4,330mm", width: "1,790mm", height: "1,580mm", weight: "1,250〜1,450kg",
    seats: 5, trunk: "約404L",
    features: ["都市型コンパクトSUV", "e:HEV", "パノラマルーフ", "Honda CONNECT"],
    talkPoints: ["クーペライクなデザインがスタイリッシュで若者に人気", "ハイブリッドの力強い加速は一度体験すると忘れられない", "後席の広さと荷室の使い勝手が抜群", "コンパクトSUVの中でもデザイン性はトップクラス"],
    rivals: ["トヨタ カローラクロス", "マツダ CX-30", "日産 キックス"],
    emoji: "🚙", popular: true
  },
  {
    id: 14, maker: "ホンダ", name: "ステップワゴン", type: "ミニバン", years: "2022〜現行(6代目)",
    newPrice: "305〜384万円", engine: "1.5Lターボ/2.0L e:HEV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "13.1〜20.0km/L(WLTC)", drive: "FF",
    length: "4,800〜4,830mm", width: "1,750mm", height: "1,840〜1,845mm", weight: "1,680〜1,840kg",
    seats: 7, trunk: "大容量",
    features: ["シンプルモダンデザイン", "AIR/SPADAの2タイプ", "3列目床下収納", "わくわくゲート廃止"],
    talkPoints: ["無駄を削ぎ落としたシンプルデザインが大人の雰囲気", "AIRは柔らかい印象、SPADAは精悍な顔つきで選べる", "3列目が床下にすっぽり収まる便利設計", "e:HEVはミニバンとは思えない静粛性"],
    rivals: ["トヨタ ヴォクシー", "日産 セレナ", "トヨタ ノア"],
    emoji: "🚐", popular: false
  },
  {
    id: 15, maker: "ホンダ", name: "フリード", type: "ミニバン", years: "2024〜現行(3代目)",
    newPrice: "250〜343万円", engine: "1.5L/1.5L e:HEV", fuel: "ハイブリッド/ガソリン(レギュラー)",
    fuelEco: "15.6〜25.6km/L(WLTC)", drive: "FF/4WD",
    length: "4,265〜4,310mm", width: "1,720mm", height: "1,755mm", weight: "1,340〜1,480kg",
    seats: 6, trunk: "コンパクト3列",
    features: ["コンパクトミニバン", "6人/7人乗り選択", "e:HEV搭載", "Honda SENSING 360"],
    talkPoints: ["ちょうどいいサイズで3列シート、日本の道にピッタリ", "フルモデルチェンジで質感が大幅アップ", "2列目キャプテンシートなら3列目へのアクセスも楽々", "Honda SENSING 360で全方位安全を実現"],
    rivals: ["トヨタ シエンタ", "スズキ ソリオ"],
    emoji: "🚐", popular: true
  },
  {
    id: 16, maker: "日産", name: "ノート", type: "コンパクト", years: "2020〜現行(3代目)",
    newPrice: "229〜287万円", engine: "1.2L e-POWER(発電用)", fuel: "ガソリン(レギュラー)※発電用",
    fuelEco: "28.4〜34.8km/L(WLTC)", drive: "FF/4WD",
    length: "4,045mm", width: "1,695mm", height: "1,520mm", weight: "1,190〜1,340kg",
    seats: 5, trunk: "約340L",
    features: ["e-POWER専用", "第2世代e-POWER", "プロパイロット", "100%モーター駆動"],
    talkPoints: ["エンジンで発電しモーターで走る独自のe-POWERシステム", "アクセルペダルだけで加減速できるワンペダル走行が楽しい", "モーター駆動ならではの静かで力強い加速", "プロパイロットで高速道路の長距離運転が楽になる"],
    rivals: ["トヨタ ヤリス", "ホンダ フィット", "マツダ MAZDA2"],
    emoji: "🚗", popular: true
  },
  {
    id: 17, maker: "日産", name: "セレナ", type: "ミニバン", years: "2022〜現行(6代目)",
    newPrice: "276〜479万円", engine: "2.0L/1.4L e-POWER", fuel: "ガソリン(レギュラー)",
    fuelEco: "13.0〜20.6km/L(WLTC)", drive: "FF/4WD",
    length: "4,690〜4,765mm", width: "1,695〜1,715mm", height: "1,870〜1,895mm", weight: "1,610〜1,850kg",
    seats: 8, trunk: "大容量",
    features: ["5ナンバーミニバン", "e-POWER搭載", "プロパイロット2.0", "ハンズオフドライブ"],
    talkPoints: ["唯一の5ナンバーミニバンで8人乗れる効率設計", "プロパイロット2.0はハンズオフ運転まで対応", "2列目超ロングスライドで足元広々", "e-POWERモデルは力強くて静かな走り"],
    rivals: ["トヨタ ヴォクシー", "ホンダ ステップワゴン", "トヨタ ノア"],
    emoji: "🚐", popular: true
  },
  {
    id: 18, maker: "日産", name: "エクストレイル", type: "SUV", years: "2022〜現行(4代目)",
    newPrice: "319〜449万円", engine: "1.5L VCターボ e-POWER", fuel: "ガソリン(レギュラー)※発電用",
    fuelEco: "18.3〜19.7km/L(WLTC)", drive: "FF/4WD(e-4ORCE)",
    length: "4,660mm", width: "1,840mm", height: "1,720mm", weight: "1,740〜1,880kg",
    seats: 5, trunk: "約575L",
    features: ["e-POWER専用SUV", "可変圧縮比エンジン", "e-4ORCE", "防水シート"],
    talkPoints: ["世界初の可変圧縮比エンジンを発電に使う革新技術", "e-4ORCEは4輪を緻密に制御して悪路も安心", "アウトドア好きに嬉しい防水シートオプション", "荷室575Lは大きなキャンプ用品も余裕で積める"],
    rivals: ["トヨタ ハリアー", "マツダ CX-5", "ホンダ ZR-V"],
    emoji: "🚙", popular: true
  },
  {
    id: 19, maker: "マツダ", name: "CX-5", type: "SUV", years: "2017〜現行(2代目)",
    newPrice: "290〜407万円", engine: "2.0L/2.5L/2.2Lディーゼル", fuel: "ガソリン(レギュラー)/ディーゼル",
    fuelEco: "13.0〜17.4km/L(WLTC)", drive: "FF/4WD",
    length: "4,575mm", width: "1,845mm", height: "1,690mm", weight: "1,510〜1,680kg",
    seats: 5, trunk: "約505L",
    features: ["魂動デザイン", "SKYACTIV技術", "ディーゼルモデル人気", "G-ベクタリングコントロール"],
    talkPoints: ["マツダの魂動デザインは欧州車のような美しさ", "ディーゼルモデルは力強いトルクと優れた燃費を両立", "内装の質感は価格以上の高級感があると評判", "ドライバーの意のままに操れる運転の楽しさ"],
    rivals: ["トヨタ ハリアー", "日産 エクストレイル", "スバル フォレスター"],
    emoji: "🚙", popular: true
  },
  {
    id: 20, maker: "マツダ", name: "CX-60", type: "SUV", years: "2022〜現行",
    newPrice: "299〜626万円", engine: "2.5L/3.3Lディーゼル/PHEV", fuel: "ディーゼル/ガソリン/PHEV",
    fuelEco: "12.5〜21.1km/L(WLTC)", drive: "FR/4WD",
    length: "4,740mm", width: "1,890mm", height: "1,685mm", weight: "1,680〜2,050kg",
    seats: 5, trunk: "約570L",
    features: ["ラージプラットフォーム", "直6ディーゼル", "FR基本", "PHEVあり"],
    talkPoints: ["マツダ初のFRベース大型SUVで走りが根本的に違う", "直列6気筒ディーゼルは国産車では唯一の存在", "PHEVなら日常はEV走行、遠出はエンジンと使い分け", "内装はナッパレザーで欧州プレミアムブランドに匹敵"],
    rivals: ["トヨタ ハリアー", "BMW X3", "ボルボ XC60"],
    emoji: "🚙", popular: false
  },
  {
    id: 21, maker: "マツダ", name: "MAZDA3", type: "セダン/HB", years: "2019〜現行",
    newPrice: "228〜368万円", engine: "1.5L/2.0L/1.8Lディーゼル", fuel: "ガソリン(レギュラー)/ディーゼル",
    fuelEco: "15.8〜20.0km/L(WLTC)", drive: "FF/4WD",
    length: "4,460mm", width: "1,795mm", height: "1,440mm", weight: "1,320〜1,530kg",
    seats: 5, trunk: "約334L",
    features: ["ワールドカーデザイン受賞", "SKYACTIV-X", "引き算の美学", "マツダコネクト"],
    talkPoints: ["ワールドカーデザイン賞を受賞した世界が認めた美しさ", "ファストバックの流れるようなデザインは唯一無二", "走る喜びを大切にするマツダらしい運転の楽しさ", "同価格帯では最も内装の質感が高いと好評"],
    rivals: ["トヨタ プリウス", "ホンダ シビック", "スバル インプレッサ"],
    emoji: "🚗", popular: false
  },
  {
    id: 22, maker: "スバル", name: "フォレスター", type: "SUV", years: "2024〜現行(6代目)",
    newPrice: "306〜374万円", engine: "2.5L 水平対向4気筒", fuel: "ガソリン(レギュラー)",
    fuelEco: "13.6〜14.0km/L(WLTC)", drive: "AWD(常時全輪駆動)",
    length: "4,640mm", width: "1,820mm", height: "1,730mm", weight: "1,570〜1,640kg",
    seats: 5, trunk: "約520L",
    features: ["シンメトリカルAWD", "X-MODE", "水平対向エンジン", "ドライバーモニタリング"],
    talkPoints: ["スバル自慢のシンメトリカルAWDで雪道も安心感が違う", "水平対向エンジンは低重心で峠道もスイスイ", "アウトドア好きの方に根強い人気がある", "X-MODEで悪路走破性は本格SUV並み"],
    rivals: ["トヨタ RAV4", "マツダ CX-5", "日産 エクストレイル"],
    emoji: "🚙", popular: false
  },
  {
    id: 23, maker: "スバル", name: "レヴォーグ", type: "ステーションワゴン", years: "2020〜現行(2代目)",
    newPrice: "310〜482万円", engine: "1.8Lターボ/2.4Lターボ", fuel: "ガソリン(レギュラー/ハイオク)",
    fuelEco: "13.5〜16.5km/L(WLTC)", drive: "AWD",
    length: "4,755mm", width: "1,795mm", height: "1,500mm", weight: "1,550〜1,600kg",
    seats: 5, trunk: "約561L",
    features: ["アイサイトX", "スポーツワゴン", "STI Sportモデル", "水平対向ターボ"],
    talkPoints: ["日本で貴重なスポーツワゴン、セダンの走りとワゴンの実用性", "アイサイトXは高速道路でハンズオフも可能", "STI Sportは走りと快適性を高次元で両立", "荷室561Lで趣味の道具もたっぷり積める"],
    rivals: ["マツダ MAZDA6", "トヨタ カローラツーリング"],
    emoji: "🚗", popular: false
  },
  {
    id: 24, maker: "スズキ", name: "スペーシア", type: "軽自動車", years: "2023〜現行(3代目)",
    newPrice: "153〜220万円", engine: "660cc/660ccターボ マイルドHV", fuel: "ガソリン(レギュラー)",
    fuelEco: "20.5〜25.1km/L(WLTC)", drive: "FF/4WD",
    length: "3,395mm", width: "1,475mm", height: "1,785mm", weight: "870〜960kg",
    seats: 4, trunk: "ハイトワゴン大容量",
    features: ["スーパーハイトワゴン", "マイルドハイブリッド", "両側パワースライドドア", "スリムサーキュレーター"],
    talkPoints: ["N-BOXのライバル、コスパの良さではこちらも負けない", "マイルドハイブリッドで燃費25km/L超え", "天井が高いので圧迫感がなく開放的", "スズキの軽量技術で軽快な走りを実現"],
    rivals: ["ホンダ N-BOX", "ダイハツ タント", "日産 ルークス"],
    emoji: "🚗", popular: true
  },
  {
    id: 25, maker: "スズキ", name: "ハスラー", type: "軽自動車", years: "2020〜現行(2代目)",
    newPrice: "136〜183万円", engine: "660cc/660ccターボ マイルドHV", fuel: "ガソリン(レギュラー)",
    fuelEco: "20.8〜25.0km/L(WLTC)", drive: "FF/4WD",
    length: "3,395mm", width: "1,475mm", height: "1,680mm", weight: "810〜890kg",
    seats: 4, trunk: "ラゲッジアンダーボックス付",
    features: ["軽クロスオーバー", "ポップなカラー", "9インチナビ", "全方位モニター"],
    talkPoints: ["遊び心のあるポップなデザインが他の車と差別化できる", "軽自動車なのにSUVテイストでアウトドアにも使える", "カラーバリエーションが豊富で自分らしい一台が見つかる", "4WDなら雪道やキャンプ場のぬかるみも安心"],
    rivals: ["ダイハツ タフト", "スズキ ジムニー"],
    emoji: "🚗", popular: true
  },
  {
    id: 26, maker: "スズキ", name: "ジムニー", type: "軽自動車(SUV)", years: "2018〜現行(4代目)",
    newPrice: "155〜208万円", engine: "660ccターボ", fuel: "ガソリン(レギュラー)",
    fuelEco: "14.3〜16.6km/L(WLTC)", drive: "パートタイム4WD",
    length: "3,395mm", width: "1,475mm", height: "1,725mm", weight: "1,030〜1,040kg",
    seats: 4, trunk: "※後席畳み時大容量",
    features: ["本格オフローダー", "ラダーフレーム", "3リンクリジッド", "パートタイム4WD"],
    talkPoints: ["軽自動車で唯一の本格ラダーフレーム構造", "世界中にファンがいるアイコニックなデザイン", "新車は納期が長く中古でも値落ちしにくい人気車", "カスタムパーツが豊富で自分だけの一台を作れる"],
    rivals: ["ダイハツ タフト", "スズキ ハスラー"],
    emoji: "🚙", popular: true
  },
  {
    id: 27, maker: "ダイハツ", name: "タント", type: "軽自動車", years: "2019〜現行(4代目)",
    newPrice: "135〜200万円", engine: "660cc/660ccターボ", fuel: "ガソリン(レギュラー)",
    fuelEco: "20.0〜22.7km/L(WLTC)", drive: "FF/4WD",
    length: "3,395mm", width: "1,475mm", height: "1,755mm", weight: "880〜950kg",
    seats: 4, trunk: "ハイトワゴン",
    features: ["ミラクルオープンドア", "DNGA採用", "スマートアシスト", "ウェルカムオープン"],
    talkPoints: ["助手席側のピラーをなくしたミラクルオープンドアが便利", "お子様の乗せ降ろしがとても楽で子育てママに大人気", "スマートアシストで安全面も充実", "低床設計でお年寄りの乗り降りも安心"],
    rivals: ["ホンダ N-BOX", "スズキ スペーシア", "日産 ルークス"],
    emoji: "🚗", popular: true
  },
  {
    id: 28, maker: "ダイハツ", name: "ロッキー", type: "SUV", years: "2019〜現行",
    newPrice: "167〜234万円", engine: "1.0Lターボ/1.2L e-SMART HV", fuel: "ガソリン(レギュラー)/HV",
    fuelEco: "17.4〜28.0km/L(WLTC)", drive: "FF/4WD",
    length: "3,995mm", width: "1,695mm", height: "1,620mm", weight: "970〜1,110kg",
    seats: 5, trunk: "約369L",
    features: ["コンパクトSUV", "5ナンバーSUV", "e-SMART HYBRID", "17インチアルミ"],
    talkPoints: ["5ナンバーで取り回しやすいSUV", "e-SMARTハイブリッドは28km/Lの好燃費", "トヨタ ライズの兄弟車で信頼性も安心", "手頃な価格でSUVライフを始められる"],
    rivals: ["トヨタ ライズ", "スズキ クロスビー"],
    emoji: "🚙", popular: false
  },
  {
    id: 29, maker: "三菱", name: "アウトランダーPHEV", type: "SUV", years: "2021〜現行(3代目)",
    newPrice: "484〜570万円", engine: "2.4L PHEV", fuel: "プラグインハイブリッド(レギュラー)",
    fuelEco: "16.2km/L(WLTC) EV航続87km", drive: "4WD(S-AWC)",
    length: "4,710mm", width: "1,860mm", height: "1,745mm", weight: "2,010〜2,110kg",
    seats: 7, trunk: "約463L",
    features: ["プラグインHV専用", "EV走行87km", "S-AWC", "V2H対応"],
    talkPoints: ["EVで87km走れるのでほぼ日常はガソリン不要", "災害時に家に電気を供給できるV2H対応が安心", "三菱自慢のS-AWCで雪道や悪路も安定感抜群", "SUVなのに7人乗りでファミリーにも対応"],
    rivals: ["トヨタ RAV4 PHV", "ホンダ CR-V", "日産 エクストレイル"],
    emoji: "🚙", popular: false
  },
  {
    id: 30, maker: "三菱", name: "デリカD:5", type: "ミニバン(SUV)", years: "2019〜現行(マイチェン)",
    newPrice: "400〜460万円", engine: "2.2Lディーゼルターボ", fuel: "ディーゼル(軽油)",
    fuelEco: "13.6km/L(WLTC)", drive: "4WD",
    length: "4,800mm", width: "1,795mm", height: "1,875mm", weight: "1,930〜1,960kg",
    seats: 7, trunk: "大容量",
    features: ["唯一無二のオフロードミニバン", "クリーンディーゼル", "スーパーセレクト4WD", "高い最低地上高"],
    talkPoints: ["ミニバンなのに本格的な悪路走破性を持つ唯一の存在", "キャンプや釣りなどアウトドア好きに熱狂的ファン多し", "ディーゼルなので軽油で経済的、トルクも力強い", "スキー場や山道でも安心して走れる頼もしさ"],
    rivals: ["トヨタ ヴォクシー", "日産 セレナ"],
    emoji: "🚐", popular: false
  },
  {
    id: 31, maker: "レクサス", name: "NX", type: "SUV", years: "2021〜現行(2代目)",
    newPrice: "455〜738万円", engine: "2.5L HV/2.4Lターボ/PHEV", fuel: "ハイブリッド/ガソリン(ハイオク)/PHEV",
    fuelEco: "14.4〜22.2km/L(WLTC)", drive: "FF/4WD",
    length: "4,660mm", width: "1,865mm", height: "1,660mm", weight: "1,710〜1,990kg",
    seats: 5, trunk: "約520L",
    features: ["レクサスのベストセラーSUV", "LEXUS Interface", "Mark Levinson", "デジタルラッチ"],
    talkPoints: ["レクサスブランドならではの上質さと安心のアフターケア", "NX450h+はPHEVでEV走行88kmと実用的", "レクサスの中ではお手頃で初レクサスにもおすすめ", "細部まで行き届いた品質は所有する喜びが違う"],
    rivals: ["BMW X3", "メルセデス GLC", "ボルボ XC60"],
    emoji: "🚙", popular: false
  },
  {
    id: 32, maker: "レクサス", name: "RX", type: "SUV", years: "2022〜現行(5代目)",
    newPrice: "664〜900万円", engine: "2.4Lターボ/2.5L HV/PHEV", fuel: "ハイブリッド/ガソリン(ハイオク)/PHEV",
    fuelEco: "14.4〜20.2km/L(WLTC)", drive: "FF/4WD",
    length: "4,890mm", width: "1,920mm", height: "1,700mm", weight: "1,880〜2,100kg",
    seats: 5, trunk: "約612L",
    features: ["プレミアムSUVの代名詞", "スピンドルボディ", "14インチディスプレイ", "DIRECT4"],
    talkPoints: ["世界的に大人気のプレミアムSUV、ステータス性が高い", "RX500hはスポーツカーのような俊敏さを持つSUV", "レクサスオーナーズラウンジなど特別な体験がある", "品質と信頼性は世界トップクラス"],
    rivals: ["BMW X5", "メルセデス GLE", "ポルシェ カイエン"],
    emoji: "🚙", popular: false
  },
  {
    id: 33, maker: "トヨタ", name: "ライズ", type: "SUV", years: "2019〜現行",
    newPrice: "171〜233万円", engine: "1.0Lターボ/1.2L e-SMART HV", fuel: "ガソリン(レギュラー)/HV",
    fuelEco: "17.4〜28.0km/L(WLTC)", drive: "FF/4WD",
    length: "3,995mm", width: "1,695mm", height: "1,620mm", weight: "970〜1,100kg",
    seats: 5, trunk: "約369L",
    features: ["コンパクトSUV", "5ナンバー", "ダイハツOEM", "手頃な価格"],
    talkPoints: ["170万円台から買えるSUVで若い方の初SUVに最適", "5ナンバーで狭い道もスイスイ、でもSUVの存在感あり", "e-SMARTハイブリッドなら28km/Lの低燃費", "トヨタブランドの安心感で選ばれる方が多い"],
    rivals: ["ダイハツ ロッキー", "スズキ クロスビー", "日産 キックス"],
    emoji: "🚙", popular: false
  },
  {
    id: 34, maker: "トヨタ", name: "RAV4", type: "SUV", years: "2019〜現行(5代目)",
    newPrice: "293〜434万円", engine: "2.0L/2.5L HV", fuel: "ガソリン(レギュラー)/ハイブリッド",
    fuelEco: "15.2〜21.4km/L(WLTC)", drive: "FF/4WD(E-Four/ダイナミックトルク)",
    length: "4,600mm", width: "1,855mm", height: "1,685mm", weight: "1,500〜1,700kg",
    seats: 5, trunk: "約580L",
    features: ["世界戦略SUV", "Adventure仕様", "ダイナミックトルクベクタリング", "PHVモデルあり"],
    talkPoints: ["世界で最も売れているSUVの一つ、グローバルで実績十分", "Adventureグレードは無骨なデザインでアウトドア映え", "ダイナミックトルクベクタリング4WDは本格的な走破性", "RAV4 PHVは306馬力でスポーツカー並みの加速"],
    rivals: ["ホンダ CR-V", "マツダ CX-5", "スバル フォレスター"],
    emoji: "🚙", popular: false
  },
  {
    id: 35, maker: "日産", name: "ルークス", type: "軽自動車", years: "2020〜現行",
    newPrice: "163〜213万円", engine: "660cc/660ccターボ", fuel: "ガソリン(レギュラー)",
    fuelEco: "18.2〜20.9km/L(WLTC)", drive: "FF/4WD",
    length: "3,395mm", width: "1,475mm", height: "1,780mm", weight: "960〜1,030kg",
    seats: 4, trunk: "ハイトワゴン",
    features: ["プロパイロット搭載軽", "ハンズフリースライドドア", "アラウンドビューモニター", "日産コネクト"],
    talkPoints: ["軽自動車初のプロパイロット搭載で高速が楽", "日産のSUV技術が活きた安定した走り", "アラウンドビューモニターで駐車が苦手な方も安心", "質感の高い内装で軽自動車のイメージが変わる"],
    rivals: ["ホンダ N-BOX", "スズキ スペーシア", "ダイハツ タント"],
    emoji: "🚗", popular: false
  },
  {
    id: 36, maker: "トヨタ", name: "アクア", type: "コンパクト", years: "2021〜現行(2代目)",
    newPrice: "199〜260万円", engine: "1.5L ハイブリッド", fuel: "ハイブリッド(レギュラー)",
    fuelEco: "29.3〜35.8km/L(WLTC)", drive: "FF/E-Four",
    length: "4,050mm", width: "1,695mm", height: "1,485mm", weight: "1,080〜1,170kg",
    seats: 5, trunk: "約300L",
    features: ["バイポーラ型ニッケル水素電池", "快感ペダル", "ディスプレイオーディオ", "コネクティッド"],
    talkPoints: ["燃費35.8km/Lは世界トップクラスの低燃費", "バイポーラ型電池は世界初採用の最新技術", "コンパクトで街乗り最強、駐車もラクラク", "ガソリン代を気にしたくない方に最適な一台"],
    rivals: ["ホンダ フィット", "日産 ノート", "トヨタ ヤリス"],
    emoji: "🚗", popular: false
  }
];
